export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const PRODUCT_CREATE_REVIEW_REQUEST = "PRODUCT_CREATE_REVIEW_REQUEST";
export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUCT_CREATE_REVIEW_SUCCESS";
export const PRODUCT_CREATE_REVIEW_FAIL = "PRODUCT_CREATE_REVIEW_FAIL";
export const PRODUCT_CREATE_REVIEW_RESET = "PRODUCT_CREATE_REVIEW_RESET";

export const PRODUCT_CREATE_BOOKING_REQUEST = "PRODUCT_CREATE_REVIEW_REQUEST";
export const PRODUCT_CREATE_BOOKING_SUCCESS = "PRODUCT_CREATE_REVIEW_SUCCESS";
export const PRODUCT_CREATE_BOOKING_FAIL = "PRODUCT_CREATE_REVIEW_FAIL";
export const PRODUCT_CREATE_BOOKING_RESET = "PRODUCT_CREATE_REVIEW_RESET";

export const PRODUCT_CREATE_GALLARY_REQUEST = "PRODUCT_CREATE_GALLARY_REQUEST";
export const PRODUCT_CREATE_GALLARY_SUCCESS = "PRODUCT_CREATE_GALLARY_SUCCESS";
export const PRODUCT_CREATE_GALLARY_FAIL = "PRODUCT_CREATE_GALLARY_FAIL";
export const PRODUCT_CREATE_GALLARY_RESET = "PRODUCT_CREATE_GALLARY_RESET";

export const PRODUCT_CREATE_DAYS_REQUEST = "PRODUCT_CREATE_DAYS_REQUEST";
export const PRODUCT_CREATE_DAYS_SUCCESS = "PRODUCT_CREATE_DAYS_SUCCESS";
export const PRODUCT_CREATE_DAYS_FAIL = "PRODUCT_CREATE_DAYS_FAIL";
export const PRODUCT_CREATE_DAYS_RESET = "PRODUCT_CREATE_DAYS_RESET";

export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";
